name: Mantener Lista Activa

on:
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas para mantener el enlace vivo
  workflow_dispatch: # Permite activarlo manualmente

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Actualizar historial
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "# Actualizado el $(date)" >> README.md
          git add README.md
          git commit -m "Refrescando enlace de la lista" || exit 0
          git push
